language: java
jdk:
  - oraclejdk8

# Cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Before Install
before_install:
  - chmod +x gradlew
  - ./gradlew install

# Build
script:
    - ./gradlew testIntegration

# Deploy (only if tags is there - default branch is master)
deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    on:
      condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
